[tool.poetry]
name = "survey-generator"
version = "0.1.0"
description = ""
authors = ["Author Anonymous <author@anonymous.com>"]
readme = "README.md"
packages = [
    { include = "survey_generator" }
]

[tool.poetry.dependencies]
python = "3.13.3"
numpy = "2.2.3"
pandas = "^2.2.3"
scikit-learn = "^1.6.1"
liac-arff = "^2.5.0"
river = "0.22.0"
seaborn= "0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arff = "survey_generator.main:generate_arff"
drift = "survey_generator.main:detect_drift"
